/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminCrawlerHealthRouteImport } from './routes/admin/crawler-health'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminUnmatchedCreditsRouteImport } from './routes/admin/unmatched-credits'
import { Route as AnimeIndexRouteImport } from './routes/anime.index'
import { Route as AnimeSlugRouteImport } from './routes/anime.$slug'
import { Route as ApiCrawlerFreshnessRouteImport } from './routes/api/crawler-freshness'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as VoiceActorsIndexRouteImport } from './routes/voice-actors.index'
import { Route as VoiceActorsSlugRouteImport } from './routes/voice-actors.$slug'
import { Route as WorksIdRouteImport } from './routes/works.$id'
import { Route as AnimeSeasonSeasonRouteImport } from './routes/anime.season.$season'
import { Route as ApiAdminActorAttributesRouteImport } from './routes/api/admin/actor-attributes'
import { Route as ApiAdminActorKanaRouteImport } from './routes/api/admin/actor-kana'
import { Route as ApiAdminActorsRouteImport } from './routes/api/admin/actors'
import { Route as ApiAdminAnilistRouteImport } from './routes/api/admin/anilist'
import { Route as ApiAdminIngestRouteImport } from './routes/api/admin/ingest'
import { Route as ApiAdminKnownIdsRouteImport } from './routes/api/admin/known-ids'
import { Route as ApiAdminPushDigestRouteImport } from './routes/api/admin/push-digest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrawlerHealthRoute = AdminCrawlerHealthRouteImport.update({
  id: '/admin/crawler-health',
  path: '/admin/crawler-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnmatchedCreditsRoute = AdminUnmatchedCreditsRouteImport.update({
  id: '/admin/unmatched-credits',
  path: '/admin/unmatched-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeSlugRoute = AnimeSlugRouteImport.update({
  id: '/anime/$slug',
  path: '/anime/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrawlerFreshnessRoute = ApiCrawlerFreshnessRouteImport.update({
  id: '/api/crawler-freshness',
  path: '/api/crawler-freshness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceActorsIndexRoute = VoiceActorsIndexRouteImport.update({
  id: '/voice-actors/',
  path: '/voice-actors/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceActorsSlugRoute = VoiceActorsSlugRouteImport.update({
  id: '/voice-actors/$slug',
  path: '/voice-actors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksIdRoute = WorksIdRouteImport.update({
  id: '/works/$id',
  path: '/works/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeSeasonSeasonRoute = AnimeSeasonSeasonRouteImport.update({
  id: '/anime/season/$season',
  path: '/anime/season/$season',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActorAttributesRoute = ApiAdminActorAttributesRouteImport.update({
  id: '/api/admin/actor-attributes',
  path: '/api/admin/actor-attributes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActorKanaRoute = ApiAdminActorKanaRouteImport.update({
  id: '/api/admin/actor-kana',
  path: '/api/admin/actor-kana',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActorsRoute = ApiAdminActorsRouteImport.update({
  id: '/api/admin/actors',
  path: '/api/admin/actors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAnilistRoute = ApiAdminAnilistRouteImport.update({
  id: '/api/admin/anilist',
  path: '/api/admin/anilist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIngestRoute = ApiAdminIngestRouteImport.update({
  id: '/api/admin/ingest',
  path: '/api/admin/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminKnownIdsRoute = ApiAdminKnownIdsRouteImport.update({
  id: '/api/admin/known-ids',
  path: '/api/admin/known-ids',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPushDigestRoute = ApiAdminPushDigestRouteImport.update({
  id: '/api/admin/push-digest',
  path: '/api/admin/push-digest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/following': typeof FollowingRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/crawler-health': typeof AdminCrawlerHealthRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/unmatched-credits': typeof AdminUnmatchedCreditsRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/api/crawler-freshness': typeof ApiCrawlerFreshnessRoute
  '/api/health': typeof ApiHealthRoute
  '/voice-actors/$slug': typeof VoiceActorsSlugRoute
  '/works/$id': typeof WorksIdRoute
  '/anime/': typeof AnimeIndexRoute
  '/voice-actors/': typeof VoiceActorsIndexRoute
  '/anime/season/$season': typeof AnimeSeasonSeasonRoute
  '/api/admin/actor-attributes': typeof ApiAdminActorAttributesRoute
  '/api/admin/actor-kana': typeof ApiAdminActorKanaRoute
  '/api/admin/actors': typeof ApiAdminActorsRoute
  '/api/admin/anilist': typeof ApiAdminAnilistRoute
  '/api/admin/ingest': typeof ApiAdminIngestRoute
  '/api/admin/known-ids': typeof ApiAdminKnownIdsRoute
  '/api/admin/push-digest': typeof ApiAdminPushDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/following': typeof FollowingRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/crawler-health': typeof AdminCrawlerHealthRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/unmatched-credits': typeof AdminUnmatchedCreditsRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/api/crawler-freshness': typeof ApiCrawlerFreshnessRoute
  '/api/health': typeof ApiHealthRoute
  '/voice-actors/$slug': typeof VoiceActorsSlugRoute
  '/works/$id': typeof WorksIdRoute
  '/anime': typeof AnimeIndexRoute
  '/voice-actors': typeof VoiceActorsIndexRoute
  '/anime/season/$season': typeof AnimeSeasonSeasonRoute
  '/api/admin/actor-attributes': typeof ApiAdminActorAttributesRoute
  '/api/admin/actor-kana': typeof ApiAdminActorKanaRoute
  '/api/admin/actors': typeof ApiAdminActorsRoute
  '/api/admin/anilist': typeof ApiAdminAnilistRoute
  '/api/admin/ingest': typeof ApiAdminIngestRoute
  '/api/admin/known-ids': typeof ApiAdminKnownIdsRoute
  '/api/admin/push-digest': typeof ApiAdminPushDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/following': typeof FollowingRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/crawler-health': typeof AdminCrawlerHealthRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/unmatched-credits': typeof AdminUnmatchedCreditsRoute
  '/anime/$slug': typeof AnimeSlugRoute
  '/api/crawler-freshness': typeof ApiCrawlerFreshnessRoute
  '/api/health': typeof ApiHealthRoute
  '/voice-actors/$slug': typeof VoiceActorsSlugRoute
  '/works/$id': typeof WorksIdRoute
  '/anime/': typeof AnimeIndexRoute
  '/voice-actors/': typeof VoiceActorsIndexRoute
  '/anime/season/$season': typeof AnimeSeasonSeasonRoute
  '/api/admin/actor-attributes': typeof ApiAdminActorAttributesRoute
  '/api/admin/actor-kana': typeof ApiAdminActorKanaRoute
  '/api/admin/actors': typeof ApiAdminActorsRoute
  '/api/admin/anilist': typeof ApiAdminAnilistRoute
  '/api/admin/ingest': typeof ApiAdminIngestRoute
  '/api/admin/known-ids': typeof ApiAdminKnownIdsRoute
  '/api/admin/push-digest': typeof ApiAdminPushDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/following'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/crawler-health'
    | '/admin/inquiries'
    | '/admin/unmatched-credits'
    | '/anime/$slug'
    | '/api/crawler-freshness'
    | '/api/health'
    | '/voice-actors/$slug'
    | '/works/$id'
    | '/anime/'
    | '/voice-actors/'
    | '/anime/season/$season'
    | '/api/admin/actor-attributes'
    | '/api/admin/actor-kana'
    | '/api/admin/actors'
    | '/api/admin/anilist'
    | '/api/admin/ingest'
    | '/api/admin/known-ids'
    | '/api/admin/push-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/following'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/crawler-health'
    | '/admin/inquiries'
    | '/admin/unmatched-credits'
    | '/anime/$slug'
    | '/api/crawler-freshness'
    | '/api/health'
    | '/voice-actors/$slug'
    | '/works/$id'
    | '/anime'
    | '/voice-actors'
    | '/anime/season/$season'
    | '/api/admin/actor-attributes'
    | '/api/admin/actor-kana'
    | '/api/admin/actors'
    | '/api/admin/anilist'
    | '/api/admin/ingest'
    | '/api/admin/known-ids'
    | '/api/admin/push-digest'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/following'
    | '/manifest.webmanifest'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/crawler-health'
    | '/admin/inquiries'
    | '/admin/unmatched-credits'
    | '/anime/$slug'
    | '/api/crawler-freshness'
    | '/api/health'
    | '/voice-actors/$slug'
    | '/works/$id'
    | '/anime/'
    | '/voice-actors/'
    | '/anime/season/$season'
    | '/api/admin/actor-attributes'
    | '/api/admin/actor-kana'
    | '/api/admin/actors'
    | '/api/admin/anilist'
    | '/api/admin/ingest'
    | '/api/admin/known-ids'
    | '/api/admin/push-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FollowingRoute: typeof FollowingRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminCrawlerHealthRoute: typeof AdminCrawlerHealthRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminUnmatchedCreditsRoute: typeof AdminUnmatchedCreditsRoute
  AnimeSlugRoute: typeof AnimeSlugRoute
  ApiCrawlerFreshnessRoute: typeof ApiCrawlerFreshnessRoute
  ApiHealthRoute: typeof ApiHealthRoute
  VoiceActorsSlugRoute: typeof VoiceActorsSlugRoute
  WorksIdRoute: typeof WorksIdRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
  VoiceActorsIndexRoute: typeof VoiceActorsIndexRoute
  AnimeSeasonSeasonRoute: typeof AnimeSeasonSeasonRoute
  ApiAdminActorAttributesRoute: typeof ApiAdminActorAttributesRoute
  ApiAdminActorKanaRoute: typeof ApiAdminActorKanaRoute
  ApiAdminActorsRoute: typeof ApiAdminActorsRoute
  ApiAdminAnilistRoute: typeof ApiAdminAnilistRoute
  ApiAdminIngestRoute: typeof ApiAdminIngestRoute
  ApiAdminKnownIdsRoute: typeof ApiAdminKnownIdsRoute
  ApiAdminPushDigestRoute: typeof ApiAdminPushDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/crawler-health': {
      id: '/admin/crawler-health'
      path: '/admin/crawler-health'
      fullPath: '/admin/crawler-health'
      preLoaderRoute: typeof AdminCrawlerHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unmatched-credits': {
      id: '/admin/unmatched-credits'
      path: '/admin/unmatched-credits'
      fullPath: '/admin/unmatched-credits'
      preLoaderRoute: typeof AdminUnmatchedCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/': {
      id: '/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$slug': {
      id: '/anime/$slug'
      path: '/anime/$slug'
      fullPath: '/anime/$slug'
      preLoaderRoute: typeof AnimeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crawler-freshness': {
      id: '/api/crawler-freshness'
      path: '/api/crawler-freshness'
      fullPath: '/api/crawler-freshness'
      preLoaderRoute: typeof ApiCrawlerFreshnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-actors/': {
      id: '/voice-actors/'
      path: '/voice-actors'
      fullPath: '/voice-actors/'
      preLoaderRoute: typeof VoiceActorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-actors/$slug': {
      id: '/voice-actors/$slug'
      path: '/voice-actors/$slug'
      fullPath: '/voice-actors/$slug'
      preLoaderRoute: typeof VoiceActorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$id': {
      id: '/works/$id'
      path: '/works/$id'
      fullPath: '/works/$id'
      preLoaderRoute: typeof WorksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/season/$season': {
      id: '/anime/season/$season'
      path: '/anime/season/$season'
      fullPath: '/anime/season/$season'
      preLoaderRoute: typeof AnimeSeasonSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/actor-attributes': {
      id: '/api/admin/actor-attributes'
      path: '/api/admin/actor-attributes'
      fullPath: '/api/admin/actor-attributes'
      preLoaderRoute: typeof ApiAdminActorAttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/actor-kana': {
      id: '/api/admin/actor-kana'
      path: '/api/admin/actor-kana'
      fullPath: '/api/admin/actor-kana'
      preLoaderRoute: typeof ApiAdminActorKanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/actors': {
      id: '/api/admin/actors'
      path: '/api/admin/actors'
      fullPath: '/api/admin/actors'
      preLoaderRoute: typeof ApiAdminActorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/anilist': {
      id: '/api/admin/anilist'
      path: '/api/admin/anilist'
      fullPath: '/api/admin/anilist'
      preLoaderRoute: typeof ApiAdminAnilistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ingest': {
      id: '/api/admin/ingest'
      path: '/api/admin/ingest'
      fullPath: '/api/admin/ingest'
      preLoaderRoute: typeof ApiAdminIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/known-ids': {
      id: '/api/admin/known-ids'
      path: '/api/admin/known-ids'
      fullPath: '/api/admin/known-ids'
      preLoaderRoute: typeof ApiAdminKnownIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/push-digest': {
      id: '/api/admin/push-digest'
      path: '/api/admin/push-digest'
      fullPath: '/api/admin/push-digest'
      preLoaderRoute: typeof ApiAdminPushDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FollowingRoute: FollowingRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminCrawlerHealthRoute: AdminCrawlerHealthRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminUnmatchedCreditsRoute: AdminUnmatchedCreditsRoute,
  AnimeSlugRoute: AnimeSlugRoute,
  ApiCrawlerFreshnessRoute: ApiCrawlerFreshnessRoute,
  ApiHealthRoute: ApiHealthRoute,
  VoiceActorsSlugRoute: VoiceActorsSlugRoute,
  WorksIdRoute: WorksIdRoute,
  AnimeIndexRoute: AnimeIndexRoute,
  VoiceActorsIndexRoute: VoiceActorsIndexRoute,
  AnimeSeasonSeasonRoute: AnimeSeasonSeasonRoute,
  ApiAdminActorAttributesRoute: ApiAdminActorAttributesRoute,
  ApiAdminActorKanaRoute: ApiAdminActorKanaRoute,
  ApiAdminActorsRoute: ApiAdminActorsRoute,
  ApiAdminAnilistRoute: ApiAdminAnilistRoute,
  ApiAdminIngestRoute: ApiAdminIngestRoute,
  ApiAdminKnownIdsRoute: ApiAdminKnownIdsRoute,
  ApiAdminPushDigestRoute: ApiAdminPushDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
